"use strict";
exports.__esModule = true;
var classify_1 = require("./utils/classify");
exports.classify = classify_1.classify;
var connect_1 = require("./utils/connect");
exports.connect = connect_1.connect;
var Context_1 = require("./utils/Context");
exports.Content = Context_1.Content;
var Svg_1 = require("./utils/Svg");
exports.SVG = Svg_1.SVG;
var parser_1 = require("./utils/parser");
exports.Parser = parser_1["default"];
