version: 2.1

jobs:
    build:
        docker:
            - image: circleci/node:8.11.1
        steps:
            - checkout
            - run: npm install
            - run: npm run build
            - run: npm run test
