"use strict";
exports.__esModule = true;
var classify_1 = require("./src/classify");
exports.classify = classify_1.classify;
var connect_1 = require("./src/connect");
exports.connect = connect_1.connect;
var Content_1 = require("./src/Content");
exports.Content = Content_1.Content;
var Svg_1 = require("./src/Svg");
exports.SVG = Svg_1.SVG;
var parser_1 = require("./src/parser");
exports.Parser = parser_1["default"];
