name: Publish library

on:
  push:
    paths: 
      -  '*.json'
      -  'src/**'
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install packages
      run: |
        yarn    
      env:
        NPM_TOKEN: secrets.NPM_TOKEN            
    - name: Build
      run: |
        yarn build
      env:
        NPM_TOKEN: secrets.NPM_TOKEN                 
    - name: Test
      run: |
        yarn test 
      env:
        NPM_TOKEN: secrets.NPM_TOKEN                 
    - name: Publish
      run: 
        npm run npm:publish        
      env:
        NPM_TOKEN: ${{secrets.NPM_TOKEN}}
