name: Publish library

on:
  push:
    paths: 
      -  '*.json'
      -  'src/**'
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install packages
      run: |
        yarn        
    - name: Build
      run: |
        yarn build
    - name: Test
      run: |
        yarn test 
    - name: Publish
      run: 
        echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc
        npm run npm:publish        
      env:
        CI: true
